mypoll/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('polls/', include('polls.urls')),
    path('admin/', admin.site.urls),
]

polls/urls.py
from django.urls import path

from . import views

app_name = 'polls'
urlpatterns = [
    path('', views.index, name='index'),
	path('category_science/', views.category_science, name='category_science'),
	path('category_lifestyle/', views.category_lifestyle, name='category_lifestyle'),
	path('category_opinion/', views.category_opinion, name='category_opinion'),
	path('category_general/', views.category_general, name='category_general'),
    path('<int:question_id>/', views.detail, name='detail'),
    path('<int:question_id>/results/', views.results, name='results'),
    path('<int:question_id>/vote/', views.vote, name='vote'),
	path('question_list/', views.question_list, name='question_list'),
	path('latest_questions/', views.latest_questions, name='latest_questions'),
]

polls/models.py
from django.db import models

from django.utils import timezone
class Category(models.Model):
	
	category_text = models.CharField(max_length=200)
	def __str__(self):
		return self.category_text
class Question(models.Model):
	question_text = models.CharField(max_length=200)
	pub_date = models.DateTimeField('date published')
	category = models.ForeignKey(Category, on_delete=models.CASCADE)
	def __str__(self):
		return self.question_text


class Choice(models.Model):
	question = models.ForeignKey(Question, on_delete=models.CASCADE)
	choice_text = models.CharField(max_length=200)
	votes = models.IntegerField(default=0)
	def __str__(self):
		return self.choice_text

polls/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.template import loader

from .models import Choice, Question,Category


def index(request):
    category_list = Category.objects.values('category_text')
    template = loader.get_template('polls/index.html')
    context = {
        'category_list': category_list,
    }
    return HttpResponse(template.render(context, request))
def category_science(request):
	q="Science"
	question_list = Question.objects.filter(category_id=1)[:50]
	template = loader.get_template('polls/t1.html')
	context = {
        'question_list': question_list,
		'category':q,
    }
	return HttpResponse(template.render(context, request))
def category_general(request):
	pass
	q="General"
	question_list = Question.objects.filter(category_id=4)[:50]
	template = loader.get_template('polls/t1.html')
	context = {
        'question_list': question_list,
		'category':q,
    }
	return HttpResponse(template.render(context, request))
def category_lifestyle(request):
	pass
	q="Lifestyle"
	question_list = Question.objects.filter(category_id=2)[:50]
	template = loader.get_template('polls/t1.html')
	context = {
        'question_list': question_list,
		'category':q,
    }
	return HttpResponse(template.render(context, request))
def category_opinion(request):
	pass
	q="Opinion"
	question_list = Question.objects.filter(category_id=3)[:50]
	template = loader.get_template('polls/t1.html')
	context = {
        'question_list': question_list,
		'category':q,
    }
	return HttpResponse(template.render(context, request))
	
def detail(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, 'polls/detail.html', {'question': question})
def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        select_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        
        return render(request, 'polls/detail.html', {
            'question': question,
            'error_message': "Select a choice then click the vote button",
        })
    else:
        select_choice.votes += 1
        select_choice.save()
        return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))
def question_list(request):
	question_list=Question.objects.order_by('id')
	template = loader.get_template('polls/list.html')
	context = {
		'question_list': question_list,
    }
	return HttpResponse(template.render(context, request))
def latest_questions(request):
	question_list=Question.objects.order_by('-pub_date')[:10]
	template = loader.get_template('polls/latest.html')
	context = {
		'question_list': question_list,
    }
	return HttpResponse(template.render(context, request))



def results(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, 'polls/results.html', {'question': question})

polls/templates/polls/detail.html
<!DOCTYPE html>
<html lang="en">
<head><title>Question {{question.id}}</title>
<meta charset="UTF-8">
 <meta name="viewport" content="width=device-width, initial-scale=1">
 <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
 <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
 <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
 <style>


body, html {
    height: 100%;
    margin: 0;
}

.bg {
    
    background-image: url("https://images.pexels.com/photos/122458/pexels-photo-122458.jpeg?auto=compress&cs=tinysrgb&h=350");

   
    height: 100%; 

    
    background-position: center;
    background-repeat: no-repeat;
    background-size: cover;
}
.list-group a:hover {
background-color:#CCB2AD;}
</style>
<script> 
$(document).ready(function(){
    $(".dropdown-toggle").click(function(){
        $(".dropdown-menu").slideToggle("slow");
    });
	$(".dropdown-menu").mouseleave(function(){
        $(".dropdown-menu").slideToggle("slow");
    });
	
});
</script>
</head>
<body>
<nav class="navbar navbar-inverse navbar-fixed-top" style="background-image: url('https://images.pexels.com/photos/235985/pexels-photo-235985.jpeg')">
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'polls:index' %}" style="margin-left:70px ;font-size:20px"><span class="glyphicon glyphicon-home" > <b>Home</b></span></a>
        </div>
        <div class="collapse navbar-collapse" id="myNavbar">
            <ul class="nav navbar-nav" style="padding-left:50px; font-family: 'Times New Roman' ;font-size:20px">
                <li class="dropdown active"><a class="dropdown-toggle" data-toggle="dropdown" href="{% url 'polls:index' %}">Categories <span class="caret"></span></a>
        <ul class="dropdown-menu">
          <li><a href="{% url 'polls:category_science' %}">Science</a></li>
          <li><a href="{% url 'polls:category_lifestyle' %}">Lifestyle</a></li>
          <li><a href="{% url 'polls:category_opinion' %}">Opinion</a></li>
		  <li><a href="{% url 'polls:category_general' %}">General</a></li>
        </ul>
      </li>
                <li><a href="{% url 'polls:question_list' %}">Question List</a></li>
                <li><a href="{% url 'polls:latest_questions' %}">Latest Questions</a></li>
            </ul>
        </div>
    </div>
</nav>
<div class="bg">
<div class= "container" style="width: 80%;color: #1a242f;padding-top:80px"><br><br>
<h3 style="text-align:right;margin-right:20px"><b>Date published : {{question.pub_date}}</b></h3>
<div class="panel-group">
<div class="panel panel-danger">
<div class="panel-heading"><h1>{{ question.question_text }}</h1>{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}</div>
<div class="panel-body"><form action="{% url 'polls:vote' question.id %}" method="post">
{% csrf_token %}
{% for choice in question.choice_set.all %}
    <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}" />
    <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br />
{% endfor %}
<button type="button submit" class="btn btn-success" >Vote</button>
</form></div></div></div>
{% if question.category_id is 1 %}
<a href="{% url 'polls:category_science' %}" ><button type="button " class="btn btn-success" style="color:black" >Go back to the questions page</button></a>
<a href="{% url 'polls:index' %}" ><button type="button" class="btn btn-success" style="color:black"> Back to the Category selection page</button></a>
{% elif question.category_id is 2 %}
<a href="{% url 'polls:category_lifestyle' %}" ><button type="button " class="btn btn-success" style="color:black" >Go back to the questions page</button></a>
<a href="{% url 'polls:index' %}" ><button type="button" class="btn btn-success" style="color:black"> Back to the Category selection page</button></a>
{% elif question.category_id is 3 %}
<a href="{% url 'polls:category_opinion' %}" ><button type="button " class="btn btn-success" style="color:black" >Go back to the questions page</button></a>
<a href="{% url 'polls:index' %}" ><button type="button" class="btn btn-success" style="color:black"> Back to the Category selection page</button></a>
{% elif question.category_id is 4 %}
<a href="{% url 'polls:category_general' %}" ><button type="button " class="btn btn-success" style="color:black" >Go back to the questions page</button></a>
<a href="{% url 'polls:index' %}" ><button type="button" class="btn btn-success" style="color:black"> Back to the Category selection page</button></a>
{% endif %}
</div>
</div></body></html>






	

polls/templates/polls/index.html
<!DOCTYPE html>
<html lang="en">
<head><title>Welcome to polls</title>
 <meta charset="UTF-8">
 <meta name="viewport" content="width=device-width, initial-scale=1">
 <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
 <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
 <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
 <style>


body, html {
    height: 100%;
    margin: 0;
}

.bg {
    
    background-image: url("https://images.pexels.com/photos/122458/pexels-photo-122458.jpeg?auto=compress&cs=tinysrgb&h=350");

   
    height: 100%; 

    
    background-position: center;
    background-repeat: no-repeat;
    background-size: cover;
}
</style>
<script> 
$(document).ready(function(){
    $(".dropdown-toggle").click(function(){
        $(".dropdown-menu").slideToggle("slow");
    });
	$(".dropdown-menu").mouseleave(function(){
        $(".dropdown-menu").slideToggle("slow");
    });
	
});
</script>
</head>
<body>
<nav class="navbar navbar-inverse navbar-fixed-top" style="background-image: url('https://images.pexels.com/photos/235985/pexels-photo-235985.jpeg')">
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'polls:index' %}" style="margin-left:70px ;font-size:20px"><span class="glyphicon glyphicon-home" > <b>Home</b></span></a>
        </div>
        <div class="collapse navbar-collapse" id="myNavbar">
            <ul class="nav navbar-nav" style="padding-left:50px; font-family: 'Times New Roman' ;font-size:20px">
                <li class="dropdown active"><a class="dropdown-toggle" data-toggle="dropdown" href="{% url 'polls:index' %}">Categories <span class="caret"></span></a>
        <ul class="dropdown-menu">
          <li><a href="{% url 'polls:category_science' %}">Science</a></li>
          <li><a href="{% url 'polls:category_lifestyle' %}">Lifestyle</a></li>
          <li><a href="{% url 'polls:category_opinion' %}">Opinion</a></li>
		  <li><a href="{% url 'polls:category_general' %}">General</a></li>
        </ul>
      </li>
               <li><a href="{% url 'polls:question_list' %}">Question List</a></li>
                <li><a href="{% url 'polls:latest_questions' %}">Latest Questions</a></li>
            </ul>
        </div>
    </div>
</nav>
<br><br><div class="bg">
<div class= "container" style="width: 80%;color: #1a242f;padding-top:80px">
<h1 style=" text-align: center;font-family: verdana"><b>Select the category</b></h1><br>
{% if category_list %}
	<div class="list-group">
    <a href="{% url 'polls:category_science'%}" class="list-group-item list-group-item-success"><h3>Science Category</h3></a>
	<a href="{% url 'polls:category_lifestyle'%}" class="list-group-item"><h3>Lifestyle Category</h3></a>
	<a href="{% url 'polls:category_opinion'%}" class="list-group-item list-group-item-success"><h3>Opinion Category</h3></a>
	<a href="{% url 'polls:category_general'%}" class="list-group-item"><h3>General Category</h3></a> 
	</div>
{% else %}
    <p>No Categories are available.</p>
{% endif %}</div></div>
</body>
</html>

polls/templates/polls/latest.html
<!DOCTYPE html>
<html lang="en">
<head><title>Latest Question list</title>
 <meta charset="UTF-8">
 <meta name="viewport" content="width=device-width, initial-scale=1">
 <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
 <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
 <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
 <style>


body, html {
    height: 100%;
    margin: 0;
}

.bg {
    
    background-image: url("https://images.pexels.com/photos/122458/pexels-photo-122458.jpeg?auto=compress&cs=tinysrgb&h=350");

   
    height: 100%; 

    
    background-position: center;
    background-repeat: no-repeat;
    background-size: cover;
}
.list-group a:hover {
background-color:#CCB2AD;}
</style>
<script> 
$(document).ready(function(){
    $(".dropdown-toggle").click(function(){
        $(".dropdown-menu").slideToggle("slow");
    });
	$(".dropdown-menu").mouseleave(function(){
        $(".dropdown-menu").slideToggle("slow");
    });
	
});
</script>
</head>
<body>
<nav class="navbar navbar-inverse navbar-fixed-top" style="background-image: url('https://images.pexels.com/photos/235985/pexels-photo-235985.jpeg')">
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'polls:index' %}" style="margin-left:70px ;font-size:20px"><span class="glyphicon glyphicon-home" > <b>Home</b></span></a>
        </div>
        <div class="collapse navbar-collapse" id="myNavbar">
            <ul class="nav navbar-nav" style="padding-left:50px; font-family: 'Times New Roman' ;font-size:20px">
                <li class="dropdown "><a class="dropdown-toggle" data-toggle="dropdown" href="{% url 'polls:index' %}">Categories <span class="caret"></span></a>
        <ul class="dropdown-menu">
          <li><a href="{% url 'polls:category_science' %}">Science</a></li>
          <li><a href="{% url 'polls:category_lifestyle' %}">Lifestyle</a></li>
          <li><a href="{% url 'polls:category_opinion' %}">Opinion</a></li>
		  <li><a href="{% url 'polls:category_general' %}">General</a></li>
        </ul>
      </li>
                <li><a href="{% url 'polls:question_list' %}">Question List</a></li>
                <li class="active"><a href="{% url 'polls:latest_questions' %}">Latest Questions</a></li>
            </ul>
        </div>
    </div>
</nav>
<br><br><div class="bg">
<div class= "container" style="width: 80%;color: #1a242f;padding-top:80px">
<h1 style=" text-align: center;font-family: verdana"><b>Latest 10 Questions </b></h1><br>
{% if question_list %}
    <div class="list-group">
    {% for question in question_list %}
        <a href="{% url 'polls:detail' question.id %}" class="list-group-item">{{ question.question_text }}</a>
    {% endfor %}
    </div>
{% else %}
    <p>No questions  are currently available .</p>
{% endif %}</div></div></body></html>

polls/templates/polls/list.html
<!DOCTYPE html>
<html lang="en">
<head><title>Question list</title>
 <meta charset="UTF-8">
 <meta name="viewport" content="width=device-width, initial-scale=1">
 <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
 <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
 <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
 <style>


body, html {
    height: 100%;
    margin: 0;
}

.bg {
    
    background-image: url("https://images.pexels.com/photos/122458/pexels-photo-122458.jpeg?auto=compress&cs=tinysrgb&h=350");

   
    height: 100%; 

    
    background-position: center;
    background-repeat: no-repeat;
    background-size: cover;
}
.list-group a:hover {
background-color:#CCB2AD;}
</style>
<script> 
$(document).ready(function(){
    $(".dropdown-toggle").click(function(){
        $(".dropdown-menu").slideToggle("slow");
    });
	$(".dropdown-menu").mouseleave(function(){
        $(".dropdown-menu").slideToggle("slow");
    });
	
});
</script>
</head>
<body>
<nav class="navbar navbar-inverse navbar-fixed-top" style="background-image: url('https://images.pexels.com/photos/235985/pexels-photo-235985.jpeg')">
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'polls:index' %}" style="margin-left:70px ;font-size:20px"><span class="glyphicon glyphicon-home" > <b>Home</b></span></a>
        </div>
        <div class="collapse navbar-collapse" id="myNavbar">
            <ul class="nav navbar-nav" style="padding-left:50px; font-family: 'Times New Roman' ;font-size:20px">
                <li class="dropdown"><a class="dropdown-toggle" data-toggle="dropdown" href="{% url 'polls:index' %}">Categories <span class="caret"></span></a>
        <ul class="dropdown-menu">
          <li><a href="{% url 'polls:category_science' %}">Science</a></li>
          <li><a href="{% url 'polls:category_lifestyle' %}">Lifestyle</a></li>
          <li><a href="{% url 'polls:category_opinion' %}">Opinion</a></li>
		  <li><a href="{% url 'polls:category_general' %}">General</a></li>
        </ul>
      </li>
                <li class="active"><a href="{% url 'polls:question_list' %}">Question List</a></li>
                <li><a href="{% url 'polls:latest_questions' %}">Latest Questions</a></li>
            </ul>
        </div>
    </div>
</nav>
<br><br><div class="bg">
<div class= "container" style="width: 80%;color: #1a242f;padding-top:80px">
<h1 style=" text-align: center;font-family: verdana"><b>All questions </b></h1><br>
{% if question_list %}
    <div class="list-group">
    {% for question in question_list %}
        <a href="{% url 'polls:detail' question.id %}" class="list-group-item">{{ question.question_text }}</a>
    {% endfor %}
    </div>
{% else %}
    <p>No questions under this category are currently available .</p>
{% endif %}</div></div></body></html>

polls/templates/polls/results.html
<!DOCTYPE html>
<html lang="en">
<head><title>Question {{question.id}}</title>
<meta charset="UTF-8">
 <meta name="viewport" content="width=device-width, initial-scale=1">
 <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
 <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
 <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

 <style>

body, html {
    height: 100%;
    margin: 0;
}

.bg {
    
    background-image: url("https://images.pexels.com/photos/122458/pexels-photo-122458.jpeg?auto=compress&cs=tinysrgb&h=350");

   
    height: 100%; 

    
    background-position: center;
    background-repeat: no-repeat;
    background-size: cover;
}
.list-group a:hover {
background-color:#CCB2AD;}
</style>
<script> 
$(document).ready(function(){
    $(".dropdown-toggle").click(function(){
        $(".dropdown-menu").slideToggle("slow");
    });
	$(".dropdown-menu").mouseleave(function(){
        $(".dropdown-menu").slideToggle("slow");
    });
	
});
</script>

</head>
<body>
<nav class="navbar navbar-inverse navbar-fixed-top" style="background-image: url('https://images.pexels.com/photos/235985/pexels-photo-235985.jpeg')">
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'polls:index' %}" style="margin-left:70px ;font-size:20px"><span class="glyphicon glyphicon-home" > <b>Home</b></span></a>
        </div>
        <div class="collapse navbar-collapse" id="myNavbar">
            <ul class="nav navbar-nav" style="padding-left:50px; font-family: 'Times New Roman' ;font-size:20px">
                <li class="dropdown active"><a class="dropdown-toggle" data-toggle="dropdown" href="{% url 'polls:index' %}">Categories <span class="caret"></span></a>
        <ul class="dropdown-menu">
          <li><a href="{% url 'polls:category_science' %}">Science</a></li>
          <li><a href="{% url 'polls:category_lifestyle' %}">Lifestyle</a></li>
          <li><a href="{% url 'polls:category_opinion' %}">Opinion</a></li>
		  <li><a href="{% url 'polls:category_general' %}">General</a></li>
        </ul>
      </li>
             <li><a href="{% url 'polls:question_list' %}">Question List</a></li>
                <li><a href="{% url 'polls:latest_questions' %}">Latest Questions</a></li>
            </ul>
        </div>
    </div>
</nav>
<div class="bg">
<div class= "container" style="width: 80%;color: #1a242f;padding-top:80px">
<div class="panel-group">
<div class="panel panel-danger">
<div class="panel-heading">
<h1>{{ question.question_text }}</h1></div>
<div class="panel-body">
<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} ---> {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul></div></div></div>

<button type="button" class="btn btn-success" ><a href="{% url 'polls:detail' question.id %}" style="color:black">Do you want to vote again?</a></button></div>
</div></body></html>

polls/templates/polls/t1.html
<!DOCTYPE html>
<html lang="en">
<head><title>Welcome to {{category}} polls</title>
<meta charset="UTF-8">
 <meta name="viewport" content="width=device-width, initial-scale=1">
 <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
 <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
 <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
 <style>

body, html {
    height: 100%;
    margin: 0;
}

.bg {
    
    background-image: url("https://images.pexels.com/photos/122458/pexels-photo-122458.jpeg?auto=compress&cs=tinysrgb&h=350");

   
    height: 100%; 

    
    background-position: center;
    background-repeat: no-repeat;
    background-size: cover;
}
.list-group a:hover {
background-color:#CCB2AD;}
</style>
<script> 
$(document).ready(function(){
    $(".dropdown-toggle").click(function(){
        $(".dropdown-menu").slideToggle("slow");
    });
	$(".dropdown-menu").mouseleave(function(){
        $(".dropdown-menu").slideToggle("slow");
    });
	
});
</script>
</head>
<body>
<nav class="navbar navbar-inverse navbar-fixed-top" style="background-image: url('https://images.pexels.com/photos/235985/pexels-photo-235985.jpeg')">
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'polls:index' %}" style="margin-left:70px ;font-size:20px"><span class="glyphicon glyphicon-home" > <b>Home</b></span></a>
        </div>
        <div class="collapse navbar-collapse" id="myNavbar">
            <ul class="nav navbar-nav" style="padding-left:50px; font-family: 'Times New Roman' ;font-size:20px">
                <li class="dropdown active"><a class="dropdown-toggle" data-toggle="dropdown" href="{% url 'polls:index' %}">Categories <span class="caret"></span></a>
        <ul class="dropdown-menu">
          <li><a href="{% url 'polls:category_science' %}">Science</a></li>
          <li><a href="{% url 'polls:category_lifestyle' %}">Lifestyle</a></li>
          <li><a href="{% url 'polls:category_opinion' %}">Opinion</a></li>
		  <li><a href="{% url 'polls:category_general' %}">General</a></li>
        </ul>
      </li>
            <li><a href="{% url 'polls:question_list' %}">Question List</a></li>
                <li><a href="{% url 'polls:latest_questions' %}">Latest Questions</a></li>
            </ul>
        </div>
    </div>
</nav><br><br><div class="bg">
<div class= "container" style="width: 80%;color: #1a242f;padding-top:80px">
<h1 style=" text-align: center;font-family: verdana"><b>Select the question</b></h1><br>
{% if question_list %}
    <div class="list-group">
    {% for question in question_list %}
        <a href="{% url 'polls:detail' question.id %}" class="list-group-item">{{ question.question_text }}</a>
    {% endfor %}
    </div>
{% else %}
    <p>No questions under this category are currently available .</p>
{% endif %}
<a href="{% url 'polls:index' %}" ><button type="button" class="btn btn-success" style="color:black"> Back to the Category selection page</button></a></div>
</body>
</html>